### PR TITLE
Added phantomjs v2.0.0 binary tested on a Lambda function.

### PR DESCRIPTION
**Pull request by ben-poole**

### CODE REVIEW

**Comment by clementai** [comment]
did you test to use render with your binary ?

Because I tried your binary using this phantomjs script and it fail with this `Error: Command failed:` ?

```
import webpage from 'webpage';
import system from 'system';

if (system.args.length === 1) {
  console.log('This script need an url');
  phantom.exit();
}

const address = system.args[1];
const pngName = [address.split('.')[address.split('.').length - 2], 'png'].join('.');

const page = webpage.create();

page.open(address, (status) => {
  if (status !== 'success') {
    console.log('Failed to load this address');
    phantom.exit();
  }
  console.log('Title :', page.title);
  page.render(pngName);
  phantom.exit();
});
```

**Comment by justengland** [comment]
It looks like you are using ES6, as far as I know that is not supported. When I run it locally on my mac the script fails.

**Comment by clementai** [comment]
Oups, it's the script before babel, this is the script that goes to phantom :

``` javascript
'use strict';

var _webpage = require('webpage');

var _webpage2 = _interopRequireDefault(_webpage);

var _system = require('system');

var _system2 = _interopRequireDefault(_system);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

if (_system2.default.args.length === 1) {
  console.log('This script need an url');
  phantom.exit();
}

var address = _system2.default.args[1];
var pngName = [address.split('.')[address.split('.').length - 2], 'png'].join('.');

var page = _webpage2.default.create();

page.open(address, function (status) {
  if (status !== 'success') {
    console.log('Failed to load this address');
    phantom.exit();
  }
  console.log('Title :', page.title);
  page.render(pngName);
  phantom.exit();
});
```

It work locally, on ec2 with amazon linux, but not on lambda

**Comment by justengland** [comment]
Sorry about the late reply, but I think we have fixed this issue with the new version of phantom. If there are still problems let me know. 

I am not quite sure the best way to handle managing the phantom program, I really think it would be nice if AWS would run npm install when we pushed up to lambda, short of that, it may makes sense to build a packaging system that was executed on a AWS linux box.

**Pull request closed without merging**
